cms/config/routes.php
<?php
/**
 * Routes configuration.
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * It's loaded within the context of `Application::routes()` method which
 * receives a `RouteBuilder` instance `$routes` as method argument.
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Routing\Route\DashedRoute;
use Cake\Routing\RouteBuilder;

return static function (RouteBuilder $routes) {
/*
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `{plugin}`, `{controller}` and
 * `{action}` markers.
 */
$routes->setRouteClass(DashedRoute::class);

$routes->scope('/', function (RouteBuilder $builder) {
    /*
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, templates/Pages/home.php)...
     */
    //$builder->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);
    $builder->connect('/', ['controller' => 'Users', 'action' => 'login']);

    /*
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $builder->connect('/pages/*', 'Pages::display');

    /*
     * Connect catchall routes for all controllers.
     *
     * The `fallbacks` method is a shortcut for
     *
     * ```
     * $builder->connect('/{controller}', ['action' => 'index']);
     * $builder->connect('/{controller}/{action}/*', []);
     * ```
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $builder->fallbacks();
});

/*
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * $routes->scope('/api', function (RouteBuilder $builder) {
 *     // No $builder->applyMiddleware() here.
 *
 *     // Parse specified extensions from URLs
 *     // $builder->setExtensions(['json', 'xml']);
 *
 *     // Connect API actions here.
 * });
 * ```
 */
};

cms/src/Model/Table/ClientsTable.php
<?php
declare(strict_types=1);

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Clients Model
 *
 * @property \App\Model\Table\CompanyTypesTable&\Cake\ORM\Association\BelongsTo $CompanyTypes
 * @property \App\Model\Table\PlansTable&\Cake\ORM\Association\BelongsTo $Plans
 * @property \App\Model\Table\BillingsTable&\Cake\ORM\Association\BelongsTo $Billings
 * @property \App\Model\Table\StatesTable&\Cake\ORM\Association\BelongsTo $States
 * @property \App\Model\Table\GatewaysTable&\Cake\ORM\Association\HasMany $Gateways
 * @property \App\Model\Table\MimiasTable&\Cake\ORM\Association\HasMany $Mimias
 * @property \App\Model\Table\UsersTable&\Cake\ORM\Association\HasMany $Users
 *
 * @method \App\Model\Entity\Client newEmptyEntity()
 * @method \App\Model\Entity\Client newEntity(array $data, array $options = [])
 * @method \App\Model\Entity\Client[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Client get($primaryKey, $options = [])
 * @method \App\Model\Entity\Client findOrCreate($search, ?callable $callback = null, $options = [])
 * @method \App\Model\Entity\Client patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Client[] patchEntities(iterable $entities, array $data, array $options = [])
 * @method \App\Model\Entity\Client|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Client saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Client[]|\Cake\Datasource\ResultSetInterface|false saveMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Client[]|\Cake\Datasource\ResultSetInterface saveManyOrFail(iterable $entities, $options = [])
 * @method \App\Model\Entity\Client[]|\Cake\Datasource\ResultSetInterface|false deleteMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Client[]|\Cake\Datasource\ResultSetInterface deleteManyOrFail(iterable $entities, $options = [])
 */
class ClientsTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('clients');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->belongsTo('CompanyTypes', [
            'foreignKey' => 'company_type_id',
            'joinType' => 'INNER',
        ]);
        $this->belongsTo('Plans', [
            'foreignKey' => 'plan_id',
        ]);
        $this->belongsTo('Billings', [
            'foreignKey' => 'billing_id',
        ]);
        $this->belongsTo('States', [
            'foreignKey' => 'state_id',
            'joinType' => 'INNER',
        ]);
        $this->hasMany('Gateways', [
            'foreignKey' => 'client_id',
        ]);
        $this->hasMany('Mimias', [
            'foreignKey' => 'client_id',
        ]);
        $this->hasMany('Users', [
            'foreignKey' => 'client_id',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->nonNegativeInteger('client_tag')
            ->requirePresence('client_tag', 'create')
            ->notEmptyString('client_tag')
            ->add('client_tag', 'unique', ['rule' => 'validateUnique', 'provider' => 'table']);

        $validator
            ->scalar('name')
            ->maxLength('name', 255)
            ->requirePresence('name', 'create')
            ->notEmptyString('name');

        $validator
            ->scalar('vat')
            ->maxLength('vat', 15)
            ->requirePresence('vat', 'create')
            ->notEmptyString('vat');

        $validator
            ->notEmptyString('company_type_id');

        $validator
            ->scalar('web')
            ->maxLength('web', 255)
            ->allowEmptyString('web');

        $validator
            ->scalar('address')
            ->maxLength('address', 255)
            ->allowEmptyString('address');

        $validator
            ->scalar('country')
            ->maxLength('country', 255)
            ->requirePresence('country', 'create')
            ->notEmptyString('country');

        $validator
            ->allowEmptyString('plan_id');

        $validator
            ->allowEmptyString('billing_id');

        $validator
            ->scalar('user')
            ->maxLength('user', 255)
            ->allowEmptyString('user')
            ->add('user', 'unique', ['rule' => 'validateUnique', 'provider' => 'table']);

        $validator
            ->scalar('password')
            ->maxLength('password', 255)
            ->allowEmptyString('password');

        $validator
            ->notEmptyString('state_id');

        $validator
            ->scalar('contact')
            ->maxLength('contact', 50)
            ->requirePresence('contact', 'create')
            ->notEmptyString('contact');

        $validator
            ->email('email')
            ->requirePresence('email', 'create')
            ->notEmptyString('email');

        $validator
            ->scalar('phone')
            ->maxLength('phone', 15)
            ->requirePresence('phone', 'create')
            ->notEmptyString('phone');

        $validator
            ->boolean('act')
            ->allowEmptyString('act');

        $validator
            ->dateTime('enroll')
            ->notEmptyDateTime('enroll');

        $validator
            ->dateTime('down')
            ->allowEmptyDateTime('down');

        $validator
            ->scalar('logo')
            ->maxLength('logo', 255)
            ->allowEmptyString('logo');

        $validator
            ->scalar('note')
            ->maxLength('note', 255)
            ->allowEmptyString('note');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules): RulesChecker
    {
        $rules->add($rules->isUnique(['client_tag']), ['errorField' => 'client_tag']);
        $rules->add($rules->isUnique(['user'], ['allowMultipleNulls' => true]), ['errorField' => 'user']);
        $rules->add($rules->existsIn('company_type_id', 'CompanyTypes'), ['errorField' => 'company_type_id']);
        $rules->add($rules->existsIn('plan_id', 'Plans'), ['errorField' => 'plan_id']);
        $rules->add($rules->existsIn('billing_id', 'Billings'), ['errorField' => 'billing_id']);
        $rules->add($rules->existsIn('state_id', 'States'), ['errorField' => 'state_id']);

        return $rules;
    }
}

cms/src/Controller/ClientsController.php
<?php
declare(strict_types=1);

namespace App\Controller;

use Cake\ORM\Locator\LocatorAwareTrait;   

/**
 * Clients Controller
 *
 * @property \App\Model\Table\ClientsTable $Clients
 * @method \App\Model\Entity\Client[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
*/

class ClientsController extends AppController
{
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index()
    {
        $this->Authorization->skipAuthorization();
        $this->paginate = [
            'contain' => ['CompanyTypes', 'Plans', 'Billings', 'States'],
        ];
        $clients = $this->paginate($this->Clients);
        
        $CompanyTypes = $this->Clients->CompanyTypes->find()->all();
        $Plans        = $this->Clients->Plans->find()->all();
        $States       = $this->Clients->States->find()->all();   

        $companyType  = $this->keyvalue($CompanyTypes);
        $plans        = $this->keyvalue($Plans);
        $states       = $this->keyvalue($States);

        $this->viewBuilder()->setLayout('template_main');
        $this->set(compact('clients','companyType','plans','states'));
    }

    /**
     * View method
     *
     * @param string|null $id Client id.
     * @return \Cake\Http\Response|null|void Renders view
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
      
      $client = $this->Clients->get($id, [
          'contain' => ['CompanyTypes', 'Plans', 'Billings', 'States','Users',],
      ]);
      $this->Authorization->authorize($client);
      $this->viewBuilder()->setLayout('template_main');

      $companyTypes = $this->Clients->CompanyTypes->find('list')->all();
      $plans        = $this->Clients->Plans->find('list')->all();
      $billings     = $this->Clients->Billings->find('list')->all();
      $states       = $this->Clients->States->find('list')->all();
      

      $entity       =  $this->fetchTable('Users');
      $query        = $entity->find();
      //seach all users for this client.
      $Users        = $query->where(['client_id ='=> $id]); 
            
      $this->paginate = [
            'contain' => ['Roles',],
        ];
      $users = $this->paginate($Users);      
 
      $this->set(compact('client', 'companyTypes', 'plans', 'billings', 'states','users'));
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null|void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
      $this->Authorization->skipAuthorization();    
      $client = $this->Clients->newEmptyEntity();
      if ($this->request->is('post')) {
          $client = $this->Clients->patchEntity($client, $this->request->getData());
          if ($this->Clients->save($client)) {
              $this->Flash->success(__('The client has been saved.'));

              return $this->redirect(['action' => 'index']);
          }
          $this->Flash->error(__('The client could not be saved. Please, try again.'));
      }
      $companyTypes = $this->Clients->CompanyTypes->find('list', ['limit' => 200])->all();
      $plans        = $this->Clients->Plans->find('list', ['limit' => 200])->all();
      $billings     = $this->Clients->Billings->find('list', ['limit' => 200])->all();
      $states       = $this->Clients->States->find('list', ['limit' => 200])->all();
      $this->set(compact('client', 'companyTypes', 'plans', 'billings', 'states'));
    }

    /**
     * Edit method
     *
     * @param string|null $id Client id.
     * @return \Cake\Http\Response|null|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function edit($id = null)
    {
      $this->Authorization->skipAuthorization();
      $client = $this->Clients->get($id, [
          'contain' => [],
      ]);
      if ($this->request->is(['patch', 'post', 'put'])) {
          $client = $this->Clients->patchEntity($client, $this->request->getData());
          if ($this->Clients->save($client)) {
              $this->Flash->success(__('The client has been saved.'));

              return $this->redirect(['action' => 'view']);
          }
          $this->Flash->error(__('The client could not be saved. Please, try again.'));
      }
        $companyTypes = $this->Clients->CompanyTypes->find('list', ['limit' => 200])->all();
        $plans = $this->Clients->Plans->find('list', ['limit' => 200])->all();
        $billings = $this->Clients->Billings->find('list', ['limit' => 200])->all();
        $states = $this->Clients->States->find('list', ['limit' => 200])->all();
        $this->set(compact('client', 'companyTypes', 'plans', 'billings', 'states'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Client id.
     * @return \Cake\Http\Response|null|void Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
      $this->request->allowMethod(['post', 'delete']);
      $client = $this->Clients->get($id);
      if ($this->Clients->delete($client)) {
          $this->Flash->success(__('The client has been deleted.'));
      } else {
          $this->Flash->error(__('The client could not be deleted. Please, try again.'));
      }

      return $this->redirect(['action' => 'index']);
    }

    
}

cms/templates/Clients/add.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Client $client
 * @var \Cake\Collection\CollectionInterface|string[] $companyTypes
 * @var \Cake\Collection\CollectionInterface|string[] $plans
 * @var \Cake\Collection\CollectionInterface|string[] $billings
 * @var \Cake\Collection\CollectionInterface|string[] $states
 */
?>
<div class="row">
    <aside class="column">
        <div class="side-nav">
            <h4 class="heading"><?= __('Actions') ?></h4>
            <?= $this->Html->link(__('List Clients'), ['action' => 'index'], ['class' => 'side-nav-item']) ?>
        </div>
    </aside>
    <div class="column-responsive column-80">
        <div class="clients form content">
            <?= $this->Form->create($client) ?>
            <fieldset>
                <legend><?= __('Add Client') ?></legend>
                <?php
                    echo $this->Form->control('client_tag');
                    echo $this->Form->control('name');
                    echo $this->Form->control('vat');
                    echo $this->Form->control('company_type_id', ['options' => $companyTypes]);
                    echo $this->Form->control('web');
                    echo $this->Form->control('address');
                    echo $this->Form->control('country');
                    echo $this->Form->control('plan_id', ['options' => $plans, 'empty' => true]);
                    echo $this->Form->control('billing_id', ['options' => $billings, 'empty' => true]);
                    echo $this->Form->control('user');
                    echo $this->Form->control('password');
                    echo $this->Form->control('state_id', ['options' => $states]);
                    echo $this->Form->control('contact');
                    echo $this->Form->control('email');
                    echo $this->Form->control('phone');
                    echo $this->Form->control('act');
                    echo $this->Form->control('enroll');
                    echo $this->Form->control('down', ['empty' => true]);
                    echo $this->Form->control('logo');
                    echo $this->Form->control('note');
                ?>
            </fieldset>
            <?= $this->Form->button(__('Submit')) ?>
            <?= $this->Form->end() ?>
        </div>
    </div>
</div>

cms/templates/Clients/view_bk.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Client $client
 */
?>
<div class="row">
    <aside class="column">
        <div class="side-nav">
            <h4 class="heading"><?= __('Actions') ?></h4>
            <?= $this->Html->link(__('Edit Client'), ['action' => 'edit', $client->id], ['class' => 'side-nav-item']) ?>
            <?= $this->Form->postLink(__('Delete Client'), ['action' => 'delete', $client->id], ['confirm' => __('Are you sure you want to delete # {0}?', $client->id), 'class' => 'side-nav-item']) ?>
            <?= $this->Html->link(__('List Clients'), ['action' => 'index'], ['class' => 'side-nav-item']) ?>
            <?= $this->Html->link(__('New Client'), ['action' => 'add'], ['class' => 'side-nav-item']) ?>
        </div>
    </aside>
    <div class="column-responsive column-80">
        <div class="clients view content">
            <h3><?= h($client->name) ?></h3>
            <table>
                <tr>
                    <th><?= __('Name') ?></th>
                    <td><?= h($client->name) ?></td>
                </tr>
                <tr>
                    <th><?= __('Vat') ?></th>
                    <td><?= h($client->vat) ?></td>
                </tr>
                <tr>
                    <th><?= __('Web') ?></th>
                    <td><?= h($client->web) ?></td>
                </tr>
                <tr>
                    <th><?= __('Address') ?></th>
                    <td><?= h($client->address) ?></td>
                </tr>
                <tr>
                    <th><?= __('Country') ?></th>
                    <td><?= h($client->country) ?></td>
                </tr>
                <tr>
                    <th><?= __('Plan') ?></th>
                    <td><?= $client->has('plan') ? $this->Html->link($client->plan->id, ['controller' => 'Plans', 'action' => 'view', $client->plan->id]) : '' ?></td>
                </tr>
                <tr>
                    <th><?= __('Billing') ?></th>
                    <td><?= $client->has('billing') ? $this->Html->link($client->billing->id, ['controller' => 'Billings', 'action' => 'view', $client->billing->id]) : '' ?></td>
                </tr>
                <tr>
                    <th><?= __('User') ?></th>
                    <td><?= h($client->user) ?></td>
                </tr>
                <tr>
                    <th><?= __('State') ?></th>
                    <td><?= $client->has('state') ? $this->Html->link($client->state->id, ['controller' => 'States', 'action' => 'view', $client->state->id]) : '' ?></td>
                </tr>
                <tr>
                    <th><?= __('Contact') ?></th>
                    <td><?= h($client->contact) ?></td>
                </tr>
                <tr>
                    <th><?= __('Email') ?></th>
                    <td><?= h($client->email) ?></td>
                </tr>
                <tr>
                    <th><?= __('Phone') ?></th>
                    <td><?= h($client->phone) ?></td>
                </tr>
                <tr>
                    <th><?= __('Logo') ?></th>
                    <td><?= h($client->logo) ?></td>
                </tr>
                <tr>
                    <th><?= __('Note') ?></th>
                    <td><?= h($client->note) ?></td>
                </tr>
                <tr>
                    <th><?= __('Id') ?></th>
                    <td><?= $this->Number->format($client->id) ?></td>
                </tr>
                <tr>
                    <th><?= __('Client Tag') ?></th>
                    <td><?= $this->Number->format($client->client_tag) ?></td>
                </tr>
                <tr>
                    <th><?= __('Enroll') ?></th>
                    <td><?= h($client->enroll) ?></td>
                </tr>
                <tr>
                    <th><?= __('Down') ?></th>
                    <td><?= h($client->down) ?></td>
                </tr>
                <tr>
                    <th><?= __('Company Type') ?></th>
                    <td><?= $client->company_type->id ? __('Yes') : __('No'); ?></td>
                </tr>
                <tr>
                    <th><?= __('Act') ?></th>
                    <td><?= $client->act ? __('Yes') : __('No'); ?></td>
                </tr>
            </table>
            <div class="related">
                <h4><?= __('Related Gateways') ?></h4>
                <?php if (!empty($client->gateways)) : ?>
                <div class="table-responsive">
                    <table>
                        <tr>
                            <th><?= __('Id') ?></th>
                            <th><?= __('Gw Tag') ?></th>
                            <th><?= __('Gw Mac') ?></th>
                            <th><?= __('Mac') ?></th>
                            <th><?= __('Key Svr0') ?></th>
                            <th><?= __('Key Svr') ?></th>
                            <th><?= __('Boot') ?></th>
                            <th><?= __('Boot Init') ?></th>
                            <th><?= __('Release Version') ?></th>
                            <th><?= __('Act') ?></th>
                            <th><?= __('On Service') ?></th>
                            <th><?= __('Off Service') ?></th>
                            <th><?= __('Client Id') ?></th>
                            <th><?= __('Comment') ?></th>
                            <th class="actions"><?= __('Actions') ?></th>
                        </tr>
                        <?php foreach ($client->gateways as $gateways) : ?>
                        <tr>
                            <td><?= h($gateways->id) ?></td>
                            <td><?= h($gateways->gw_tag) ?></td>
                            <td><?= h($gateways->gw_mac) ?></td>
                            <td><?= h($gateways->mac) ?></td>
                            <td><?= h($gateways->key_svr0) ?></td>
                            <td><?= h($gateways->key_svr) ?></td>
                            <td><?= h($gateways->boot) ?></td>
                            <td><?= h($gateways->boot_Init) ?></td>
                            <td><?= h($gateways->release_version) ?></td>
                            <td><?= h($gateways->act) ?></td>
                            <td><?= h($gateways->on_service) ?></td>
                            <td><?= h($gateways->off_service) ?></td>
                            <td><?= h($gateways->client_id) ?></td>
                            <td><?= h($gateways->comment) ?></td>
                            <td class="actions">
                                <?= $this->Html->link(__('View'), ['controller' => 'Gateways', 'action' => 'view', $gateways->id]) ?>
                                <?= $this->Html->link(__('Edit'), ['controller' => 'Gateways', 'action' => 'edit', $gateways->id]) ?>
                                <?= $this->Form->postLink(__('Delete'), ['controller' => 'Gateways', 'action' => 'delete', $gateways->id], ['confirm' => __('Are you sure you want to delete # {0}?', $gateways->id)]) ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
                <?php endif; ?>
            </div>
            <div class="related">
                <h4><?= __('Related Mimias') ?></h4>
                <?php if (!empty($client->mimias)) : ?>
                <div class="table-responsive">
                    <table>
                        <tr>
                            <th><?= __('Id') ?></th>
                            <th><?= __('Mimia Tag') ?></th>
                            <th><?= __('Mm Mac') ?></th>
                            <th><?= __('Mac') ?></th>
                            <th><?= __('Mm Tk 0') ?></th>
                            <th><?= __('Slot') ?></th>
                            <th><?= __('Boot') ?></th>
                            <th><?= __('Boot Init') ?></th>
                            <th><?= __('Release Version') ?></th>
                            <th><?= __('Act') ?></th>
                            <th><?= __('On Service') ?></th>
                            <th><?= __('Off Service') ?></th>
                            <th><?= __('Client Id') ?></th>
                            <th><?= __('Comment') ?></th>
                            <th class="actions"><?= __('Actions') ?></th>
                        </tr>
                        <?php foreach ($client->mimias as $mimias) : ?>
                        <tr>
                            <td><?= h($mimias->id) ?></td>
                            <td><?= h($mimias->mimia_tag) ?></td>
                            <td><?= h($mimias->mm_mac) ?></td>
                            <td><?= h($mimias->mac) ?></td>
                            <td><?= h($mimias->mm_tk_0) ?></td>
                            <td><?= h($mimias->slot) ?></td>
                            <td><?= h($mimias->boot) ?></td>
                            <td><?= h($mimias->boot_init) ?></td>
                            <td><?= h($mimias->release_version) ?></td>
                            <td><?= h($mimias->act) ?></td>
                            <td><?= h($mimias->on_service) ?></td>
                            <td><?= h($mimias->off_service) ?></td>
                            <td><?= h($mimias->client_id) ?></td>
                            <td><?= h($mimias->comment) ?></td>
                            <td class="actions">
                                <?= $this->Html->link(__('View'), ['controller' => 'Mimias', 'action' => 'view', $mimias->id]) ?>
                                <?= $this->Html->link(__('Edit'), ['controller' => 'Mimias', 'action' => 'edit', $mimias->id]) ?>
                                <?= $this->Form->postLink(__('Delete'), ['controller' => 'Mimias', 'action' => 'delete', $mimias->id], ['confirm' => __('Are you sure you want to delete # {0}?', $mimias->id)]) ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
                <?php endif; ?>
            </div>
            <div class="related">
                <h4><?= __('Related Users') ?></h4>
                <?php if (!empty($client->users)) : ?>
                <div class="table-responsive">
                    <table>
                        <tr>
                            <th><?= __('Id') ?></th>
                            <th><?= __('User') ?></th>
                            <th><?= __('Email') ?></th>
                            <th><?= __('Password') ?></th>
                            <th><?= __('Role Id') ?></th>
                            <th><?= __('Client Id') ?></th>
                            <th><?= __('Avatar') ?></th>
                            <th><?= __('Act') ?></th>
                            <th><?= __('Created') ?></th>
                            <th><?= __('Modified') ?></th>
                            <th class="actions"><?= __('Actions') ?></th>
                        </tr>
                        <?php foreach ($client->users as $users) : ?>
                        <tr>
                            <td><?= h($users->id) ?></td>
                            <td><?= h($users->user) ?></td>
                            <td><?= h($users->email) ?></td>
                            <td><?= h($users->password) ?></td>
                            <td><?= h($users->role_id) ?></td>
                            <td><?= h($users->client_id) ?></td>
                            <td><?= h($users->avatar) ?></td>
                            <td><?= h($users->act) ?></td>
                            <td><?= h($users->created) ?></td>
                            <td><?= h($users->modified) ?></td>
                            <td class="actions">
                                <?= $this->Html->link(__('View'), ['controller' => 'Users', 'action' => 'view', $users->id]) ?>
                                <?= $this->Html->link(__('Edit'), ['controller' => 'Users', 'action' => 'edit', $users->id]) ?>
                                <?= $this->Form->postLink(__('Delete'), ['controller' => 'Users', 'action' => 'delete', $users->id], ['confirm' => __('Are you sure you want to delete # {0}?', $users->id)]) ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>